[build]
  # Install dependencies, generate the Prisma Client, then build your project.
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

  [build.environment]
    NODE_OPTIONS = "--no-warnings"

[[plugins]]
  package = "@netlify/plugin-nextjs"
